'use strict';

const calculateBtn = document.getElementById('start');
console.log(calculateBtn);
const PlusBtn1 = document.getElementsByTagName('button')[0];
console.log(PlusBtn1);
const PlusBtn2 = document.getElementsByTagName('button')[1];
console.log(PlusBtn2);
const depositCheckbox = document.querySelector('#deposit-check');
console.log(depositCheckbox);
const additionalIncomeItem = document.querySelectorAll('.additional_income-item');
console.log(additionalIncomeItem);
const budgetDayValue = document.getElementsByClassName('budget_day-value')[0];
console.log(budgetDayValue);
const expensesMonthValue = document.getElementsByClassName('expenses_month-value')[0];
console.log(expensesMonthValue);
const additionalIncomeValue = document.getElementsByClassName('additional_income-value')[0];
console.log(additionalIncomeValue);
const additionalExpensesValue = document.getElementsByClassName('additional_expenses-value')[0];
console.log(additionalExpensesValue);
const incomePeriodValue = document.getElementsByClassName('income_period-value')[0];
console.log(incomePeriodValue);
const targetMonthValue = document.getElementsByClassName('target_month-value')[0];
console.log(targetMonthValue);
const salaryAmount = document.querySelector('.salary-amount');
console.log(salaryAmount);
const incomeTitle = document.querySelector('.income-title');
console.log(incomeTitle);
const incomeAmount = document.querySelector('.income-amount');
console.log(incomeAmount);
const expensesTitle = document.querySelector('.expenses-title');
console.log(expensesTitle);
const expensesAmount = document.querySelector('.expenses-amount');
console.log(expensesAmount);
const additionalExpensesItem = document.querySelector('.additional_expenses-item');
console.log(additionalExpensesItem);
const targetAmount = document.querySelector('.target-amount');
console.log(targetAmount);
const periodSelect = document.querySelector('.period-select');
console.log(periodSelect);
const budgetMonthValue = document.getElementsByClassName('budget_month-value')[0];
console.log(budgetMonthValue);